# frozen_string_literal: true

require 'zm/client/version'

module Zm
  module Client
    autoload :Utils, 'zm/client/utils'
    autoload :ZmLogger, 'zm/client/zm_logger'
    autoload :Token, 'zm/client/token'
    autoload :Upload, 'zm/client/upload'

    autoload :Recipients, 'zm/client/recipients'
    autoload :Recipient, 'zm/client/recipient'

    autoload :LdapFilter, 'zm/client/ldap_filter'

    autoload :BatchRequest, 'zm/client/batch_request'

    autoload :MailboxItemConcern, 'zm/client/mailbox/mailbox_item_concern'
    autoload :MailboxItemID, 'zm/client/mailbox/mailbox_item_id'

    autoload :ClusterConfig, 'zm/client/cluster/cluster_config'
    autoload :Cluster, 'zm/client/cluster/cluster'

    autoload :Server, 'zm/client/server/server'
    autoload :ServerJsnsInitializer, 'zm/client/server/server_jsns_initializer'
    autoload :ServersBuilder, 'zm/client/server/servers_builder'
    autoload :ServersCollection, 'zm/client/server/servers_collection'
    autoload :ServerAccountsCollection, 'zm/client/server/server_accounts_collection'
    autoload :ServerServices, 'zm/client/server/server_services'

    autoload :Cos, 'zm/client/cos/cos'
    autoload :CosJsnsInitializer, 'zm/client/cos/cos_jsns_initializer'
    autoload :CosJsnsBuilder, 'zm/client/cos/cos_jsns_builder'
    autoload :CosesBuilder, 'zm/client/cos/coses_builder'
    autoload :CosesCollection, 'zm/client/cos/coses_collection'
    autoload :CosServersCollection, 'zm/client/cos/cos_servers_collection'
    autoload :CosDomainsCollection, 'zm/client/cos/cos_domains_collection'
    autoload :CosAccountsCollection, 'zm/client/cos/cos_accounts_collection'

    autoload :Domain, 'zm/client/domain/domain'
    autoload :DomainsBuilder, 'zm/client/domain/domains_builder'
    autoload :DomainJsnsBuilder, 'zm/client/domain/domain_jsns_builder'
    autoload :DomainJsnsInitializer, 'zm/client/domain/domain_jsns_initializer'
    autoload :DomainsCollection, 'zm/client/domain/domains_collection'
    autoload :DomainAccountsCollection, 'zm/client/domain/domain_accounts_collection'
    autoload :DomainDistributionListsCollection, 'zm/client/domain/domain_distributionlists_collection'
    autoload :DomainResourcesCollection, 'zm/client/domain/domain_resources_collection'

    autoload :Account, 'zm/client/account/account'
    autoload :AccountJsnsBuilder, 'zm/client/account/account_jsns_builder'
    autoload :AccountJsnsInitializer, 'zm/client/account/account_jsns_initializer'
    autoload :AccountsBuilder, 'zm/client/account/accounts_builder'
    autoload :AccountsCollection, 'zm/client/account/accounts_collection'
    autoload :AccountAliasesCollection, 'zm/client/account/account_aliases_collection'
    autoload :AccountDlsMembershipCollection, 'zm/client/account/account_dls_membership_collection'
    autoload :AccountDlsOwnerCollection, 'zm/client/account/account_dls_owner_collection'

    autoload :Resource, 'zm/client/resource/resource'
    autoload :ResourceJsnsBuilder, 'zm/client/resource/resource_jsns_builder'
    autoload :ResourceJsnsInitializer, 'zm/client/resource/resource_jsns_initializer'
    autoload :ResourcesBuilder, 'zm/client/resource/resources_builder'
    autoload :ResourcesCollection, 'zm/client/resource/resources_collection'

    autoload :DistributionList, 'zm/client/distributionlist/distributionlist'
    autoload :DistributionListJsnsBuilder, 'zm/client/distributionlist/distributionlist_jsns_builder'
    autoload :DistributionListJsnsInitializer, 'zm/client/distributionlist/distributionlist_jsns_initializer'
    autoload :DistributionListsBuilder, 'zm/client/distributionlist/distributionlists_builder'
    autoload :DistributionListsCollection, 'zm/client/distributionlist/distributionlists_collection'
    autoload :DlsMembershipCollection, 'zm/client/distributionlist/dls_membership_collection'
    autoload :DistributionListAliasesCollection, 'zm/client/distributionlist/distributionlist_aliases_collection'
    autoload :DistributionListMembersCollection, 'zm/client/distributionlist/distributionlist_members_collection'
    autoload :DistributionListOwnersCollection, 'zm/client/distributionlist/distributionlist_owners_collection'
    autoload :DistributionListAcesCollection, 'zm/client/distributionlist/distributionlist_aces_collection'

    autoload :License, 'zm/client/license/license'
    autoload :LicenseJsnsInitializer, 'zm/client/license/license_jsns_initializer'
    autoload :LicensesCollection, 'zm/client/license/licenses_collection'

    autoload :MtaQueueName, 'zm/client/mta_queue/mta_queue_name'
    autoload :MtaQueueAction, 'zm/client/mta_queue/mta_queue_action'

    autoload :FolderDefault, 'zm/client/folder/folder_default'
    autoload :FolderView, 'zm/client/folder/folder_view'

    autoload :Ace, 'zm/client/ace/ace'
    autoload :AceJsnsBuilder, 'zm/client/ace/ace_jsns_builder'
    autoload :AceJsnsInitializer, 'zm/client/ace/ace_jsns_initializer'
    autoload :AcesBuilder, 'zm/client/ace/aces_builder'
    autoload :AcesCollection, 'zm/client/ace/aces_collection'

    autoload :Appointment, 'zm/client/appointment/appointment'
    autoload :AppointmentJsnsBuilder, 'zm/client/appointment/appointment_jsns_builder'
    autoload :AppointmentJsnsInitializer, 'zm/client/appointment/appointment_jsns_initializer'
    autoload :AppointmentsBuilder, 'zm/client/appointment/appointments_builder'
    autoload :AppointmentsCollection, 'zm/client/appointment/appointments_collection'

    autoload :Backup, 'zm/client/backup/backup'
    autoload :BackupJsnsInitializer, 'zm/client/backup/backup_jsns_initializer'
    autoload :BackupsBuilder, 'zm/client/backup/backups_builder'
    autoload :BackupsCollection, 'zm/client/backup/backups_collection'

    autoload :DataSource, 'zm/client/datasource/datasource'
    autoload :DataSourceJsnsInitializer, 'zm/client/datasource/datasource_jsns_initializer'
    autoload :DataSourceJsnsBuilder, 'zm/client/datasource/datasource_jsns_builder'
    autoload :DataSourcesBuilder, 'zm/client/datasource/datasources_builder'
    autoload :DataSourcesCollection, 'zm/client/datasource/datasources_collection'

    autoload :Contact, 'zm/client/contact/contact'
    autoload :ContactMembersCollection, 'zm/client/contact/contact_members_collection'
    autoload :ModGroupContact, 'zm/client/contact/mod_group_contact'
    autoload :ContactJsnsInitializer, 'zm/client/contact/contact_jsns_initializer'
    autoload :ContactJsnsBuilder, 'zm/client/contact/contact_jsns_builder'
    autoload :GroupContactJsnsBuilder, 'zm/client/contact/group_contact_jsns_builder'
    autoload :ContactMember, 'zm/client/contact/contact_member'
    autoload :ContactsBuilder, 'zm/client/contact/contacts_builder'
    autoload :ContactsCollection, 'zm/client/contact/contacts_collection'

    autoload :Document, 'zm/client/document/document'
    autoload :DocumentJsnsInitializer, 'zm/client/document/document_jsns_initializer'
    autoload :DocumentJsnsBuilder, 'zm/client/document/document_jsns_builder'
    autoload :DocumentsBuilder, 'zm/client/document/documents_builder'
    autoload :DocumentsCollection, 'zm/client/document/documents_collection'

    autoload :FilterRule, 'zm/client/filter_rules/filter_rule'
    autoload :FilterRuleJsnsInitializer, 'zm/client/filter_rules/filter_rule_jsns_initializer'
    autoload :FilterRulesBuilder, 'zm/client/filter_rules/filter_rules_builder'
    autoload :FilterRulesCollection, 'zm/client/filter_rules/filter_rules_collection'
    autoload :OutgoingFilterRulesCollection, 'zm/client/filter_rules/outgoing_filter_rules_collection'

    autoload :Task, 'zm/client/task/task'
    autoload :TaskJsnsInitializer, 'zm/client/task/task_jsns_initializer'
    autoload :TasksBuilder, 'zm/client/task/tasks_builder'
    autoload :TasksCollection, 'zm/client/task/tasks_collection'

    autoload :Tag, 'zm/client/tag/tag'
    autoload :TagJsnsBuilder, 'zm/client/tag/tag_jsns_builder'
    autoload :TagJsnsInitializer, 'zm/client/tag/tag_jsns_initializer'
    autoload :TagsBuilder, 'zm/client/tag/tags_builder'
    autoload :TagsCollection, 'zm/client/tag/tags_collection'
    autoload :AccountObjectTagsCollection, 'zm/client/tag/account_object_tags_collection'

    autoload :Signature, 'zm/client/signature/signature'
    autoload :SignatureJsnsBuilder, 'zm/client/signature/signature_jsns_builder'
    autoload :SignatureJsnsInitializer, 'zm/client/signature/signature_jsns_initializer'
    autoload :SignaturesBuilder, 'zm/client/signature/signatures_builder'
    autoload :SignaturesCollection, 'zm/client/signature/signatures_collection'

    autoload :Share, 'zm/client/share/share'
    autoload :ShareJsnsInitializer, 'zm/client/share/share_jsns_initializer'
    autoload :SharesBuilder, 'zm/client/share/shares_builder'
    autoload :SharesCollection, 'zm/client/share/shares_collection'
    autoload :ShareMountPointsCollection, 'zm/client/share/share_mountpoints_collection'

    autoload :SearchFolder, 'zm/client/search_folder/search_folder'
    autoload :SearchFolderJsnsBuilder, 'zm/client/search_folder/search_folder_jsns_builder'
    autoload :SearchFolderJsnsInitializer, 'zm/client/search_folder/search_folder_jsns_initializer'
    autoload :SearchFoldersBuilder, 'zm/client/search_folder/search_folders_builder'
    autoload :SearchFoldersCollection, 'zm/client/search_folder/search_folders_collection'

    autoload :Folder, 'zm/client/folder/folder'
    autoload :FolderJsnsBuilder, 'zm/client/folder/folder_jsns_builder'
    autoload :FolderJsnsInitializer, 'zm/client/folder/folder_jsns_initializer'
    autoload :FoldersJsnsBuilder, 'zm/client/folder/folders_jsns_builder'
    autoload :FolderGrant, 'zm/client/folder/folder_grant'
    autoload :FolderGrantsCollection, 'zm/client/folder/folder_grants_collection'
    autoload :FolderGrantJsnsBuilder, 'zm/client/folder/folder_grant_jsns_builder'
    autoload :FolderRetentionPolicy, 'zm/client/folder/folder_retention_policy'
    autoload :FolderRetentionPoliciesCollection, 'zm/client/folder/folder_retention_policies_collection'
    autoload :FoldersBuilder, 'zm/client/folder/folders_builder'
    autoload :FoldersCollection, 'zm/client/folder/folders_collection'
    autoload :ModDocumentFolder, 'zm/client/folder/mod_document_folder'

    autoload :Identity, 'zm/client/identity/identity'
    autoload :IdentityJsnsBuilder, 'zm/client/identity/identity_jsns_builder'
    autoload :IdentityJsnsInitializer, 'zm/client/identity/identity_jsns_initializer'
    autoload :IdentitiesBuilder, 'zm/client/identity/identities_builder'
    autoload :IdentitiesCollection, 'zm/client/identity/identities_collection'

    autoload :MountPoint, 'zm/client/mountpoint/mountpoint'
    autoload :MountPointJsnsBuilder, 'zm/client/mountpoint/mountpoint_jsns_builder'
    autoload :MountPointJsnsInitializer, 'zm/client/mountpoint/mountpoint_jsns_initializer'
    autoload :MountPointsBuilder, 'zm/client/mountpoint/mountpoints_builder'
    autoload :MountPointsCollection, 'zm/client/mountpoint/mountpoints_collection'

    autoload :Message, 'zm/client/message/message'
    autoload :MessageFlagsCollection, 'zm/client/message/message_flags_collection'
    autoload :MessageRecipients, 'zm/client/message/message_recipients'
    autoload :MessageAttachmentsCollection, 'zm/client/message/message_attachments_collection'
    autoload :MessageJsnsBuilder, 'zm/client/message/message_jsns_builder'
    autoload :MessageJsnsInitializer, 'zm/client/message/message_jsns_initializer'
    autoload :MessagesBuilder, 'zm/client/message/messages_builder'
    autoload :MessagesCollection, 'zm/client/message/messages_collection'

    autoload :MtaQueue, 'zm/client/mta_queue/mta_queue'
    autoload :MtaQueueJsnsInitializer, 'zm/client/mta_queue/mta_queue_jsns_initializer'
    autoload :MtaQueueJsnsBuilder, 'zm/client/mta_queue/mta_queue_jsns_builder'
    autoload :MtaQueuesBuilder, 'zm/client/mta_queue/mta_queues_builder'
    autoload :MtaQueuesCollection, 'zm/client/mta_queue/mta_queues_collection'

    autoload :MtaQueueItem, 'zm/client/mta_queue_item/mta_queue_item'
    autoload :MtaQueueItemJsnsInitializer, 'zm/client/mta_queue_item/mta_queue_item_jsns_initializer'
    autoload :MtaQueueItemsBuilder, 'zm/client/mta_queue_item/mta_queue_items_builder'
    autoload :MtaQueueItemsCollection, 'zm/client/mta_queue_item/mta_queue_items_collection'

    module Base
      autoload :BaseJsnsBuilder, 'zm/client/base/base_jsns_builder'
      autoload :BaseAccountJsnsBuilder, 'zm/client/base/base_account_jsns_builder'
      autoload :BaseJsnsInitializer, 'zm/client/base/base_jsns_initializer'
      autoload :ObjectsBuilder, 'zm/client/base/objects_builder'
      autoload :ObjectsCollection, 'zm/client/base/objects_collection'
      autoload :AdminObjectsCollection, 'zm/client/base/admin_objects_collection'
      autoload :AccountObjectsCollection, 'zm/client/base/account_objects_collection'
      autoload :AccountSearchObjectsCollection, 'zm/client/base/account_search_objects_collection'
      autoload :ZimbraAttributesCollection, 'zm/client/base/zimbra_attributes_collection'
      autoload :ZimbraAttribute, 'zm/client/base/zimbra_attribute'
      autoload :Object, 'zm/client/base/object'
      autoload :MailboxObject, 'zm/client/base/mailbox_object'
      autoload :MailboxInfosCollection, 'zm/client/base/mailbox_infos_collection'
      autoload :MailboxPrefsCollection, 'zm/client/base/mailbox_prefs_collection'
    end
  end
end
