# frozen_string_literal: true

module Zm
  module Client
    module AccountAttrs
      def self.included(base)
        base.class_eval do
          extend Philosophal::Properties

          cprop :cn, String
          cprop :co, String
          cprop :company, String
          cprop :description, String
          cprop :destinationIndicator, String
          cprop :displayName, String
          cprop :facsimileTelephoneNumber, String
          cprop :givenName, String
          cprop :homePhone, String
          cprop :initials, String
          cprop :l, String
          cprop :mobile, String
          cprop :o, String
          cprop :ou, String
          cprop :pager, String
          cprop :physicalDeliveryOfficeName, String
          cprop :postOfficeBox, String
          cprop :postalAddress, String
          cprop :postalCode, String
          cprop :registeredAddress, String
          cprop :sn, String
          cprop :street, String
          cprop :telephoneNumber, String
          cprop :teletexTerminalIdentifier, String
          cprop :telexNumber, String
          cprop :thumbnailPhoto, String
          cprop :title, String
          cprop :userPassword, String
          cprop :userSMIMECertificate, Array
          cprop :x121Address, String
          cprop :zimbraACE, Array
          cprop :zimbraAccountCalendarUserType, String # USER, RESOURCE
          cprop :zimbraAccountStatus, String # active,maintenance,locked,closed,lockout,pending
          cprop :zimbraAdminAuthTokenLifetime, String
          cprop :zimbraAdminConsoleUIComponents, Array
          cprop :zimbraAdminOutgoingSieveScriptAfter, String
          cprop :zimbraAdminOutgoingSieveScriptBefore, String
          cprop :zimbraAdminSavedSearches, Array
          cprop :zimbraAdminSieveScriptAfter, String
          cprop :zimbraAdminSieveScriptBefore, String
          cprop :zimbraAllowAnyFromAddress, _Boolean
          cprop :zimbraAllowFromAddress, Array
          cprop :zimbraAppSpecificPassword, Array, immutable: true
          cprop :zimbraAppSpecificPasswordDuration, String
          cprop :zimbraArchiveAccount, Array
          cprop :zimbraArchiveAccountDateTemplate, String
          cprop :zimbraArchiveAccountNameTemplate, String
          cprop :zimbraArchiveEnabled, _Boolean
          cprop :zimbraAttachmentsBlocked, _Boolean
          cprop :zimbraAttachmentsIndexingEnabled, _Boolean
          cprop :zimbraAttachmentsViewInHtmlOnly, _Boolean
          cprop :zimbraAuthLdapExternalDn, String
          cprop :zimbraAuthTokenLifetime, String
          cprop :zimbraAuthTokenValidityValue, Integer
          cprop :zimbraAuthTokens, Array
          cprop :zimbraAvailabilityServiceProvider, _Boolean
          cprop :zimbraAvailableLocale, Array
          cprop :zimbraAvailableSkin, Array
          cprop :zimbraBatchedIndexingSize, Integer
          cprop :zimbraCOSId, String
          cprop :zimbraCalendarCalDavSharedFolderCacheDuration, String
          cprop :zimbraCalendarCalDavSyncEnd, String
          cprop :zimbraCalendarCalDavSyncStart, String
          cprop :zimbraCalendarKeepExceptionsOnSeriesTimeChange, _Boolean
          cprop :zimbraCalendarLocationDisabledFields, String
          cprop :zimbraCalendarMaxRevisions, Integer
          cprop :zimbraCalendarReminderDeviceEmail, String
          cprop :zimbraCalendarResourceDoubleBookingAllowed, _Boolean
          cprop :zimbraCalendarShowResourceTabs, _Boolean
          cprop :zimbraChatHistoryEnabled, _Boolean
          cprop :zimbraCommunityAPIClientID, String
          cprop :zimbraCommunityAPIClientSecret, String
          cprop :zimbraCommunityBaseURL, String
          cprop :zimbraCommunityHomeURL, String
          cprop :zimbraCommunityID, String
          cprop :zimbraCommunityUsernameMapping, String
          cprop :zimbraContactAutoCompleteMaxResults, Integer
          cprop :zimbraContactEmailFields, String
          cprop :zimbraContactMaxNumEntries, Integer
          cprop :zimbraContactRankingTableSize, Integer
          cprop :zimbraConverterHints, Array
          cprop :zimbraCreateTimestamp, String, immutable: true
          cprop :zimbraCustomerCareTier, Integer # 1 or 3
          cprop :zimbraDataSourceCaldavPollingInterval, String
          cprop :zimbraDataSourceCalendarPollingInterval, String
          cprop :zimbraDataSourceGalPollingInterval, String
          cprop :zimbraDataSourceImapPollingInterval, String
          cprop :zimbraDataSourceImportOnLogin, _Boolean
          cprop :zimbraDataSourceLivePollingInterval, String
          cprop :zimbraDataSourceMaxNumEntries, Integer
          cprop :zimbraDataSourceMinPollingInterval, String
          cprop :zimbraDataSourcePollingInterval, String
          cprop :zimbraDataSourcePop3PollingInterval, String
          cprop :zimbraDataSourceQuota, Integer
          cprop :zimbraDataSourceRssPollingInterval, String
          cprop :zimbraDataSourceTotalQuota, Integer
          cprop :zimbraDataSourceYabPollingInterval, String
          cprop :zimbraDebugInfo, Array
          cprop :zimbraDefaultFolderFlags, String
          cprop :zimbraDeviceAllowedPasscodeLockoutDuration, Array
          cprop :zimbraDeviceCalendarSoftDeleteExcludePattern, String
          cprop :zimbraDeviceFileOpenWithEnabled, _Boolean
          cprop :zimbraDeviceLockWhenInactive, _Boolean
          cprop :zimbraDeviceOfflineCacheEnabled, _Boolean
          cprop :zimbraDevicePasscodeEnabled, _Boolean
          cprop :zimbraDevicePasscodeLockoutDuration, String
          cprop :zimbraDisableCrossAccountConversationThreading, _Boolean
          cprop :zimbraDomainAdminMaxMailQuota, Integer
          cprop :zimbraDumpsterEnabled, _Boolean
          cprop :zimbraDumpsterPurgeEnabled, _Boolean
          cprop :zimbraDumpsterUserVisibleAge, String
          cprop :zimbraExcludeFromCMBSearch, _Boolean
          cprop :zimbraExportMaxDays, Integer
          cprop :zimbraExternalAccountDisabledTime, String
          cprop :zimbraExternalAccountLifetimeAfterDisabled, String
          cprop :zimbraExternalImapHostname, String
          cprop :zimbraExternalImapPort, Integer
          cprop :zimbraExternalImapSSLHostname, String
          cprop :zimbraExternalImapSSLPort, Integer
          cprop :zimbraExternalPop3Hostname, String
          cprop :zimbraExternalPop3Port, Integer
          cprop :zimbraExternalPop3SSLHostname, String
          cprop :zimbraExternalPop3SSLPort, Integer
          cprop :zimbraExternalShareDomainWhitelistEnabled, _Boolean
          cprop :zimbraExternalShareLifetime, String
          cprop :zimbraExternalShareWhitelistDomain, Array
          cprop :zimbraExternalSharingEnabled, _Boolean
          cprop :zimbraExternalUserMailAddress, String
          cprop :zimbraFeatureAddressUnderVerification, String
          cprop :zimbraFeatureAddressVerificationEnabled, _Boolean
          cprop :zimbraFeatureAddressVerificationExpiry, String
          cprop :zimbraFeatureAddressVerificationStatus, String
          cprop :zimbraFeatureAdminMailEnabled, _Boolean
          cprop :zimbraFeatureAdminPreferencesEnabled, _Boolean
          cprop :zimbraFeatureAdvancedSearchEnabled, _Boolean
          cprop :zimbraFeatureAntispamEnabled, _Boolean
          cprop :zimbraFeatureAppSpecificPasswordsEnabled, _Boolean
          cprop :zimbraFeatureBriefcaseDocsEnabled, _Boolean
          cprop :zimbraFeatureBriefcaseSlidesEnabled, _Boolean
          cprop :zimbraFeatureBriefcaseSpreadsheetEnabled, _Boolean
          cprop :zimbraFeatureBriefcasesEnabled, _Boolean
          cprop :zimbraFeatureCalendarEnabled, _Boolean
          cprop :zimbraFeatureCalendarReminderDeviceEmailEnabled, _Boolean
          cprop :zimbraFeatureCalendarUpsellEnabled, _Boolean
          cprop :zimbraFeatureCalendarUpsellURL, String
          cprop :zimbraFeatureChangePasswordEnabled, _Boolean
          cprop :zimbraFeatureChatEnabled, _Boolean
          cprop :zimbraFeatureComposeInNewWindowEnabled, _Boolean
          cprop :zimbraFeatureConfirmationPageEnabled, _Boolean
          cprop :zimbraFeatureContactBackupEnabled, _Boolean
          cprop :zimbraFeatureContactsDetailedSearchEnabled, _Boolean
          cprop :zimbraFeatureContactsEnabled, _Boolean
          cprop :zimbraFeatureContactsUpsellEnabled, _Boolean
          cprop :zimbraFeatureContactsUpsellURL, String
          cprop :zimbraFeatureConversationsEnabled, _Boolean
          cprop :zimbraFeatureCrocodocEnabled, _Boolean
          cprop :zimbraFeatureDataSourcePurgingEnabled, _Boolean
          cprop :zimbraFeatureDiscardInFiltersEnabled, _Boolean
          cprop :zimbraFeatureDistributionListExpandMembersEnabled, _Boolean
          cprop :zimbraFeatureDistributionListFolderEnabled, _Boolean
          cprop :zimbraFeatureEwsEnabled, _Boolean
          cprop :zimbraFeatureExportFolderEnabled, _Boolean
          cprop :zimbraFeatureExternalFeedbackEnabled, _Boolean
          cprop :zimbraFeatureFiltersEnabled, _Boolean
          cprop :zimbraFeatureFlaggingEnabled, _Boolean
          cprop :zimbraFeatureFreeBusyViewEnabled, _Boolean
          cprop :zimbraFeatureFromDisplayEnabled, _Boolean
          cprop :zimbraFeatureGalAutoCompleteEnabled, _Boolean
          cprop :zimbraFeatureGalEnabled, _Boolean
          cprop :zimbraFeatureGalSyncEnabled, _Boolean
          cprop :zimbraFeatureGroupCalendarEnabled, _Boolean
          cprop :zimbraFeatureHtmlComposeEnabled, _Boolean
          cprop :zimbraFeatureIdentitiesEnabled, _Boolean
          cprop :zimbraFeatureImapDataSourceEnabled, _Boolean
          cprop :zimbraFeatureImportFolderEnabled, _Boolean
          cprop :zimbraFeatureInitialSearchPreferenceEnabled, _Boolean
          cprop :zimbraFeatureInstantNotify, _Boolean
          cprop :zimbraFeatureMAPIConnectorEnabled, _Boolean
          cprop :zimbraFeatureMailEnabled, _Boolean
          cprop :zimbraFeatureMailForwardingEnabled, _Boolean
          cprop :zimbraFeatureMailForwardingInFiltersEnabled, _Boolean
          cprop :zimbraFeatureMailPriorityEnabled, _Boolean
          cprop :zimbraFeatureMailSendLaterEnabled, _Boolean
          cprop :zimbraFeatureMailUpsellEnabled, _Boolean
          cprop :zimbraFeatureMailUpsellURL, String
          cprop :zimbraFeatureManageSMIMECertificateEnabled, _Boolean
          cprop :zimbraFeatureManageZimlets, _Boolean
          cprop :zimbraFeatureMarkMailForwardedAsRead, _Boolean
          cprop :zimbraFeatureMobileGatewayEnabled, _Boolean
          cprop :zimbraFeatureMobilePolicyEnabled, _Boolean
          cprop :zimbraFeatureMobileSyncEnabled, _Boolean
          cprop :zimbraFeatureNewAddrBookEnabled, _Boolean
          cprop :zimbraFeatureNewMailNotificationEnabled, _Boolean
          cprop :zimbraFeatureOpenMailInNewWindowEnabled, _Boolean
          cprop :zimbraFeatureOptionsEnabled, _Boolean
          cprop :zimbraFeatureOutOfOfficeReplyEnabled, _Boolean
          cprop :zimbraFeaturePop3DataSourceEnabled, _Boolean
          cprop :zimbraFeaturePortalEnabled, _Boolean
          cprop :zimbraFeaturePriorityInboxEnabled, _Boolean
          cprop :zimbraFeatureReadReceiptsEnabled, _Boolean
          cprop :zimbraFeatureResetPasswordStatus, String # enabled,suspended,disabled
          cprop :zimbraFeatureResetPasswordSuspensionTime, String
          cprop :zimbraFeatureSMIMEEnabled, _Boolean
          cprop :zimbraFeatureSavedSearchesEnabled, _Boolean
          cprop :zimbraFeatureSharingEnabled, _Boolean
          cprop :zimbraFeatureSignaturesEnabled, _Boolean
          cprop :zimbraFeatureSkinChangeEnabled, _Boolean
          cprop :zimbraFeatureSocialEnabled, _Boolean
          cprop :zimbraFeatureSocialExternalEnabled, _Boolean
          cprop :zimbraFeatureSocialExternalURL, String
          cprop :zimbraFeatureSocialFiltersEnabled, Array # SocialCast,LinkedIn,Twitter,Facebook
          cprop :zimbraFeatureSocialName, String
          cprop :zimbraFeatureSocialcastEnabled, _Boolean
          cprop :zimbraFeatureTaggingEnabled, _Boolean
          cprop :zimbraFeatureTasksEnabled, _Boolean
          cprop :zimbraFeatureTouchClientEnabled, _Boolean
          cprop :zimbraFeatureTrustedDevicesEnabled, _Boolean
          cprop :zimbraFeatureTwoFactorAuthAvailable, _Boolean
          cprop :zimbraFeatureTwoFactorAuthRequired, _Boolean
          cprop :zimbraFeatureViewInHtmlEnabled, _Boolean
          cprop :zimbraFeatureVoiceChangePinEnabled, _Boolean
          cprop :zimbraFeatureVoiceEnabled, _Boolean
          cprop :zimbraFeatureVoiceUpsellEnabled, _Boolean
          cprop :zimbraFeatureVoiceUpsellURL, String
          cprop :zimbraFeatureWebClientOfflineAccessEnabled, _Boolean
          cprop :zimbraFeatureZimbraAssistantEnabled, _Boolean
          cprop :zimbraFileAndroidCrashReportingEnabled, _Boolean
          cprop :zimbraFileDeletionNotificationBody, String
          cprop :zimbraFileDeletionNotificationSubject, String
          cprop :zimbraFileExpirationWarningBody, String
          cprop :zimbraFileExpirationWarningSubject, String
          cprop :zimbraFileExpirationWarningThreshold, String
          cprop :zimbraFileExternalShareLifetime, String
          cprop :zimbraFileIOSCrashReportingEnabled, _Boolean
          cprop :zimbraFileLifetime, String
          cprop :zimbraFilePreviewMaxSize, Integer
          cprop :zimbraFilePublicShareLifetime, String
          cprop :zimbraFileShareLifetime, String
          cprop :zimbraFileUploadMaxSizePerFile, Integer
          cprop :zimbraFileVersionLifetime, String
          cprop :zimbraFileVersioningEnabled, _Boolean
          cprop :zimbraFilterBatchSize, Integer
          cprop :zimbraFilterSleepInterval, String
          cprop :zimbraForceClearCookies, _Boolean
          cprop :zimbraForeignPrincipal, Array
          cprop :zimbraFreebusyExchangeAuthPassword, String
          cprop :zimbraFreebusyExchangeAuthScheme, String # basic, form
          cprop :zimbraFreebusyExchangeAuthUsername, String
          cprop :zimbraFreebusyExchangeCachedInterval, String
          cprop :zimbraFreebusyExchangeCachedIntervalStart, String
          cprop :zimbraFreebusyExchangeURL, String
          cprop :zimbraFreebusyExchangeUserOrg, String
          cprop :zimbraFreebusyLocalMailboxNotActive, _Boolean
          cprop :zimbraGalSyncAccountBasedAutoCompleteEnabled, _Boolean
          cprop :zimbraHideInGal, _Boolean
          cprop :zimbraId, String, immutable: true
          cprop :zimbraIdentityMaxNumEntries, Integer
          cprop :zimbraImapEnabled, _Boolean
          cprop :zimbraInterceptAddress, String
          cprop :zimbraInterceptBody, String
          cprop :zimbraInterceptFrom, String
          cprop :zimbraInterceptSendHeadersOnly, _Boolean
          cprop :zimbraInterceptSubject, String
          cprop :zimbraInternalSendersDomain, Array
          cprop :zimbraIsAdminAccount, _Boolean
          cprop :zimbraIsCustomerCareAccount, _Boolean
          cprop :zimbraIsDelegatedAdminAccount, _Boolean
          cprop :zimbraIsDomainAdminAccount, _Boolean
          cprop :zimbraIsExternalVirtualAccount, _Boolean
          cprop :zimbraIsMobileGatewayAppAccount, _Boolean
          cprop :zimbraIsMobileGatewayProxyAccount, _Boolean
          cprop :zimbraIsSystemAccount, _Boolean
          cprop :zimbraIsSystemResource, _Boolean
          cprop :zimbraJunkMessagesIndexingEnabled, _Boolean
          cprop :zimbraLastLogonTimestamp, String, immutable: true
          cprop :zimbraLocale, String
          cprop :zimbraLogOutFromAllServers, _Boolean
          cprop :zimbraMailAlias, Array, immutable: true
          cprop :zimbraMailAllowReceiveButNotSendWhenOverQuota, _Boolean
          cprop :zimbraMailBlacklistMaxNumEntries, Integer
          cprop :zimbraMailCanonicalAddress, String
          cprop :zimbraMailCatchAllAddress, Array
          cprop :zimbraMailCatchAllCanonicalAddress, String
          cprop :zimbraMailCatchAllForwardingAddress, String
          cprop :zimbraMailDeliveryAddress, String, immutable: true
          cprop :zimbraMailDumpsterLifetime, String
          cprop :zimbraMailForwardingAddress, Array
          cprop :zimbraMailForwardingAddressMaxLength, Integer
          cprop :zimbraMailForwardingAddressMaxNumAddrs, Integer
          cprop :zimbraMailHighlightObjectsMaxSize, Integer
          cprop :zimbraMailHost, String # not update
          cprop :zimbraMailIdleSessionTimeout, String
          cprop :zimbraMailMessageLifetime, String
          cprop :zimbraMailMinPollingInterval, String
          cprop :zimbraMailOutgoingSieveScript, String
          cprop :zimbraMailPurgeUseChangeDateForSpam, _Boolean
          cprop :zimbraMailPurgeUseChangeDateForTrash, _Boolean
          cprop :zimbraMailQuota, Integer
          cprop :zimbraMailSieveScript, String
          cprop :zimbraMailSignatureMaxLength, Integer
          cprop :zimbraMailSpamLifetime, String
          cprop :zimbraMailStatus, String # enabled, disabled
          cprop :zimbraMailThreadingAlgorithm, String # subject,subjrefs,references,strict,none
          cprop :zimbraMailTransport, String # not create
          cprop :zimbraMailTrashLifetime, String
          cprop :zimbraMailTrustedSenderListMaxNumEntries, Integer
          cprop :zimbraMailWhitelistMaxNumEntries, Integer
          cprop :zimbraMailboxLocationBeforeMove, String
          cprop :zimbraMaxAppSpecificPasswords, Integer
          cprop :zimbraMaxContactsPerPage, Integer
          cprop :zimbraMaxMailItemsPerPage, Integer
          cprop :zimbraMaxVoiceItemsPerPage, Integer
          cprop :zimbraMobileAttachSkippedItemEnabled, _Boolean
          cprop :zimbraMobileForceProtocol25, _Boolean
          cprop :zimbraMobileForceSamsungProtocol25, _Boolean
          cprop :zimbraMobileItemsToTrackPerFolderMaxSize, Array
          cprop :zimbraMobileMetadataMaxSizeEnabled, _Boolean
          cprop :zimbraMobileNotificationAdminAddress, String
          cprop :zimbraMobileNotificationEnabled, _Boolean
          cprop :zimbraMobileOutlookSyncEnabled, _Boolean
          cprop :zimbraMobilePolicyAllowBluetooth, Integer
          cprop :zimbraMobilePolicyAllowBrowser, Integer
          cprop :zimbraMobilePolicyAllowCamera, Integer
          cprop :zimbraMobilePolicyAllowConsumerEmail, Integer
          cprop :zimbraMobilePolicyAllowDesktopSync, Integer
          cprop :zimbraMobilePolicyAllowHTMLEmail, Integer
          cprop :zimbraMobilePolicyAllowInternetSharing, Integer
          cprop :zimbraMobilePolicyAllowIrDA, Integer
          cprop :zimbraMobilePolicyAllowNonProvisionableDevices, _Boolean
          cprop :zimbraMobilePolicyAllowPOPIMAPEmail, Integer
          cprop :zimbraMobilePolicyAllowPartialProvisioning, _Boolean
          cprop :zimbraMobilePolicyAllowRemoteDesktop, Integer
          cprop :zimbraMobilePolicyAllowSMIMEEncryptionAlgorithmNegotiation, Integer
          cprop :zimbraMobilePolicyAllowSMIMESoftCerts, Integer
          cprop :zimbraMobilePolicyAllowSimpleDevicePassword, _Boolean
          cprop :zimbraMobilePolicyAllowStorageCard, Integer
          cprop :zimbraMobilePolicyAllowTextMessaging, Integer
          cprop :zimbraMobilePolicyAllowUnsignedApplications, Integer
          cprop :zimbraMobilePolicyAllowUnsignedInstallationPackages, Integer
          cprop :zimbraMobilePolicyAllowWiFi, Integer
          cprop :zimbraMobilePolicyAlphanumericDevicePasswordRequired, _Boolean
          cprop :zimbraMobilePolicyApprovedApplication, Array
          cprop :zimbraMobilePolicyApprovedApplicationList, Array
          cprop :zimbraMobilePolicyDevicePasswordEnabled, _Boolean
          cprop :zimbraMobilePolicyDevicePasswordExpiration, Integer
          cprop :zimbraMobilePolicyDevicePasswordHistory, Integer
          cprop :zimbraMobilePolicyMaxCalendarAgeFilter, Integer
          cprop :zimbraMobilePolicyMaxDevicePasswordFailedAttempts, Integer
          cprop :zimbraMobilePolicyMaxEmailAgeFilter, Integer
          cprop :zimbraMobilePolicyMaxEmailBodyTruncationSize, Integer
          cprop :zimbraMobilePolicyMaxEmailHTMLBodyTruncationSize, Integer
          cprop :zimbraMobilePolicyMaxInactivityTimeDeviceLock, Integer
          cprop :zimbraMobilePolicyMinDevicePasswordComplexCharacters, Integer
          cprop :zimbraMobilePolicyMinDevicePasswordLength, Integer
          cprop :zimbraMobilePolicyPasswordRecoveryEnabled, _Boolean
          cprop :zimbraMobilePolicyRefreshInterval, Integer
          cprop :zimbraMobilePolicyRequireDeviceEncryption, Integer
          cprop :zimbraMobilePolicyRequireEncryptedSMIMEMessages, Integer
          cprop :zimbraMobilePolicyRequireEncryptionSMIMEAlgorithm, Integer
          cprop :zimbraMobilePolicyRequireManualSyncWhenRoaming, Integer
          cprop :zimbraMobilePolicyRequireSignedSMIMEAlgorithm, Integer
          cprop :zimbraMobilePolicyRequireSignedSMIMEMessages, Integer
          cprop :zimbraMobilePolicyRequireStorageCardEncryption, _Boolean
          cprop :zimbraMobilePolicySuppressDeviceEncryption, _Boolean
          cprop :zimbraMobilePolicyUnapprovedInROMApplication, Array
          cprop :zimbraMobileSearchMimeSupportEnabled, _Boolean
          cprop :zimbraMobileShareContactEnabled, _Boolean
          cprop :zimbraMobileSmartForwardRFC822Enabled, _Boolean
          cprop :zimbraMobileSyncKeyFormatConvertedFolders, Array
          cprop :zimbraMobileSyncRedoMaxAttempts, Array
          cprop :zimbraMobileTombstoneEnabled, _Boolean
          cprop :zimbraNewMailNotificationBody, String
          cprop :zimbraNewMailNotificationFrom, String
          cprop :zimbraNewMailNotificationMessage, String
          cprop :zimbraNewMailNotificationSubject, String
          cprop :zimbraNotebookMaxRevisions, Integer
          cprop :zimbraNotebookSanitizeHtml, _Boolean
          cprop :zimbraNotes, String
          cprop :zimbraOAuthAccessor, Array
          cprop :zimbraPasswordAllowedChars, String
          cprop :zimbraPasswordAllowedPunctuationChars, String
          cprop :zimbraPasswordEnforceHistory, Integer
          cprop :zimbraPasswordHistory, Array, immutable: true
          cprop :zimbraPasswordLocked, _Boolean
          cprop :zimbraPasswordLockoutDuration, String
          cprop :zimbraPasswordLockoutEnabled, _Boolean
          cprop :zimbraPasswordLockoutFailureLifetime, String, immutable: true
          cprop :zimbraPasswordLockoutFailureTime, String, immutable: true
          cprop :zimbraPasswordLockoutLockedTime, String, immutable: true
          cprop :zimbraPasswordLockoutMaxFailures, Integer
          cprop :zimbraPasswordLockoutSuppressionCacheSize, Integer
          cprop :zimbraPasswordLockoutSuppressionEnabled, _Boolean
          cprop :zimbraPasswordLockoutSuppressionProtocols, Array # zsync,imap,pop3,http_basic,http_dav,soap
          cprop :zimbraPasswordMaxAge, Integer
          cprop :zimbraPasswordMaxLength, Integer
          cprop :zimbraPasswordMinAge, Integer
          cprop :zimbraPasswordMinAlphaChars, Integer
          cprop :zimbraPasswordMinDigitsOrPuncs, Integer
          cprop :zimbraPasswordMinLength, Integer
          cprop :zimbraPasswordMinLowerCaseChars, Integer
          cprop :zimbraPasswordMinNumericChars, Integer
          cprop :zimbraPasswordMinPunctuationChars, Integer
          cprop :zimbraPasswordMinUpperCaseChars, Integer
          cprop :zimbraPasswordModifiedTime, String
          cprop :zimbraPasswordMustChange, _Boolean
          cprop :zimbraPasswordRecoveryMaxAttempts, Integer
          cprop :zimbraPhoneticCompany, String
          cprop :zimbraPhoneticFirstName, String
          cprop :zimbraPhoneticLastName, String
          cprop :zimbraPop3Enabled, _Boolean
          cprop :zimbraPortalName, String
          cprop :zimbraPrefAccountTreeOpen, _Boolean
          cprop :zimbraPrefAdminConsoleWarnOnExit, _Boolean
          cprop :zimbraPrefAdvancedClientEnforceMinDisplay, _Boolean
          cprop :zimbraPrefAllowAddressForDelegatedSender, Array
          cprop :zimbraPrefAppleIcalDelegationEnabled, _Boolean
          cprop :zimbraPrefAutoAddAddressEnabled, _Boolean
          cprop :zimbraPrefAutoCompleteQuickCompletionOnComma, _Boolean
          cprop :zimbraPrefAutoSaveDraftInterval, String
          cprop :zimbraPrefBccAddress, String
          cprop :zimbraPrefBriefcaseReadingPaneLocation, String # bottom,right,off
          cprop :zimbraPrefCalendarAcceptSignatureId, String
          cprop :zimbraPrefCalendarAllowCancelEmailToSelf, _Boolean
          cprop :zimbraPrefCalendarAllowForwardedInvite, _Boolean
          cprop :zimbraPrefCalendarAllowPublishMethodInvite, _Boolean
          cprop :zimbraPrefCalendarAllowedTargetsForInviteDeniedAutoReply, String # internal,sameDomain,all
          cprop :zimbraPrefCalendarAlwaysShowMiniCal, _Boolean
          cprop :zimbraPrefCalendarApptAllowAtendeeEdit, _Boolean
          cprop :zimbraPrefCalendarApptReminderWarningTime, Integer
          cprop :zimbraPrefCalendarApptVisibility, String # public,private
          cprop :zimbraPrefCalendarAutoAcceptSignatureId, String
          cprop :zimbraPrefCalendarAutoAddInvites, _Boolean
          cprop :zimbraPrefCalendarAutoDeclineSignatureId, String
          cprop :zimbraPrefCalendarAutoDenySignatureId, String
          cprop :zimbraPrefCalendarDayHourEnd, Integer
          cprop :zimbraPrefCalendarDayHourStart, Integer
          cprop :zimbraPrefCalendarDeclineSignatureId, String
          cprop :zimbraPrefCalendarDefaultApptDuration, String
          cprop :zimbraPrefCalendarFirstDayOfWeek, Integer
          cprop :zimbraPrefCalendarForwardInvitesTo, Array
          cprop :zimbraPrefCalendarInitialCheckedCalendars, String
          cprop :zimbraPrefCalendarInitialView, String # day,week,workWeek,month,list,year
          cprop :zimbraPrefCalendarNotifyDelegatedChanges, _Boolean
          cprop :zimbraPrefCalendarReminderDeviceInfo, String
          cprop :zimbraPrefCalendarReminderEmail, String
          cprop :zimbraPrefCalendarReminderFlashTitle, _Boolean
          cprop :zimbraPrefCalendarReminderSoundsEnabled, _Boolean
          cprop :zimbraPrefCalendarSendInviteDeniedAutoReply, _Boolean
          cprop :zimbraPrefCalendarShowDeclinedMeetings, _Boolean
          cprop :zimbraPrefCalendarShowPastDueReminders, _Boolean
          cprop :zimbraPrefCalendarTentativeSignatureId, String
          cprop :zimbraPrefCalendarToasterEnabled, _Boolean
          cprop :zimbraPrefCalendarUseQuickAdd, _Boolean
          cprop :zimbraPrefCalendarViewTimeInterval, String
          cprop :zimbraPrefCalendarWorkingHours, String
          cprop :zimbraPrefChatEnabled, _Boolean
          cprop :zimbraPrefChatPlaySound, _Boolean
          cprop :zimbraPrefClientType, String # standard,advanced,zimbrax
          cprop :zimbraPrefColorMessagesEnabled, _Boolean
          cprop :zimbraPrefComposeDirection, String
          cprop :zimbraPrefComposeFormat, String
          cprop :zimbraPrefComposeInNewWindow, _Boolean
          cprop :zimbraPrefContactsPerPage, Integer
          cprop :zimbraPrefConvReadingPaneLocation, String
          cprop :zimbraPrefConvShowCalendar, _Boolean
          cprop :zimbraPrefConversationOrder, String
          cprop :zimbraPrefDedupeMessagesSentToSelf, String
          cprop :zimbraPrefDefaultCalendarId, Integer, default: 10
          cprop :zimbraPrefDefaultPrintFontSize, String
          cprop :zimbraPrefDefaultSignatureId, String
          cprop :zimbraPrefDelegatedSendSaveTarget, String
          cprop :zimbraPrefDeleteInviteOnReply, _Boolean
          cprop :zimbraPrefDisabledZimlets, Array
          cprop :zimbraPrefDisplayExternalImages, _Boolean
          cprop :zimbraPrefDisplayTimeInMailList, _Boolean
          cprop :zimbraPrefExternalSendersType, String
          cprop :zimbraPrefFileSharingApplication, String, default: 'briefcase'
          cprop :zimbraPrefFolderColorEnabled, _Boolean
          cprop :zimbraPrefFolderTreeOpen, _Boolean
          cprop :zimbraPrefFont, String
          cprop :zimbraPrefFontSize, String
          cprop :zimbraPrefForwardIncludeOriginalText, String
          cprop :zimbraPrefForwardReplyFormat, String
          cprop :zimbraPrefForwardReplyInOriginalFormat, _Boolean
          cprop :zimbraPrefForwardReplyPrefixChar, String
          cprop :zimbraPrefForwardReplySignatureId, String
          cprop :zimbraPrefFromAddress, String
          cprop :zimbraPrefFromAddressType, String, default: 'sendAs'
          cprop :zimbraPrefFromDisplay, String
          cprop :zimbraPrefGalAutoCompleteEnabled, _Boolean
          cprop :zimbraPrefGalSearchEnabled, _Boolean
          cprop :zimbraPrefGetMailAction, String
          cprop :zimbraPrefGroupMailBy, String
          cprop :zimbraPrefHtmlEditorDefaultFontColor, String
          cprop :zimbraPrefHtmlEditorDefaultFontFamily, String
          cprop :zimbraPrefHtmlEditorDefaultFontSize, String
          cprop :zimbraPrefIMToasterEnabled, _Boolean
          cprop :zimbraPrefIdentityName, String
          cprop :zimbraPrefImapSearchFoldersEnabled, _Boolean
          cprop :zimbraPrefInboxReadLifetime, String
          cprop :zimbraPrefInboxUnreadLifetime, String
          cprop :zimbraPrefIncludeSharedItemsInSearch, _Boolean
          cprop :zimbraPrefIncludeSpamInSearch, _Boolean
          cprop :zimbraPrefIncludeTrashInSearch, _Boolean
          cprop :zimbraPrefItemsPerVirtualPage, Integer
          cprop :zimbraPrefJunkLifetime, String
          cprop :zimbraPrefLabel, String
          cprop :zimbraPrefListViewColumns, String
          cprop :zimbraPrefLocale, String
          cprop :zimbraPrefMailDefaultCharset, String
          cprop :zimbraPrefMailFlashIcon, _Boolean
          cprop :zimbraPrefMailFlashTitle, _Boolean
          cprop :zimbraPrefMailFoldersCheckedForNewMsgIndicator, String
          cprop :zimbraPrefMailForwardingAddress, String
          cprop :zimbraPrefMailInitialSearch, String
          cprop :zimbraPrefMailItemsPerPage, Integer
          cprop :zimbraPrefMailLocalDeliveryDisabled, _Boolean
          cprop :zimbraPrefMailPollingInterval, String
          cprop :zimbraPrefMailRequestReadReceipts, _Boolean
          cprop :zimbraPrefMailSelectAfterDelete, String
          cprop :zimbraPrefMailSendReadReceipts, String
          cprop :zimbraPrefMailSignature, String
          cprop :zimbraPrefMailSignatureContactId, String
          cprop :zimbraPrefMailSignatureEnabled, _Boolean
          cprop :zimbraPrefMailSignatureHTML, String
          cprop :zimbraPrefMailSignatureStyle, String
          cprop :zimbraPrefMailSoundsEnabled, _Boolean
          cprop :zimbraPrefMailToasterEnabled, _Boolean
          cprop :zimbraPrefMailTrustedSenderList, Array
          cprop :zimbraPrefMandatorySpellCheckEnabled, _Boolean
          cprop :zimbraPrefMarkMsgRead, Integer
          cprop :zimbraPrefMessageIdDedupingEnabled, _Boolean
          cprop :zimbraPrefMessageViewHtmlPreferred, _Boolean
          cprop :zimbraPrefNewMailNotificationAddress, String
          cprop :zimbraPrefNewMailNotificationEnabled, _Boolean
          cprop :zimbraPrefOpenMailInNewWindow, _Boolean
          cprop :zimbraPrefOutOfOfficeCacheDuration, String
          cprop :zimbraPrefOutOfOfficeDirectAddress, Array
          cprop :zimbraPrefOutOfOfficeExternalReply, String
          cprop :zimbraPrefOutOfOfficeExternalReplyEnabled, _Boolean
          cprop :zimbraPrefOutOfOfficeFreeBusyStatus, String
          cprop :zimbraPrefOutOfOfficeFromDate, String
          cprop :zimbraPrefOutOfOfficeReply, String
          cprop :zimbraPrefOutOfOfficeReplyEnabled, _Boolean
          cprop :zimbraPrefOutOfOfficeSpecificDomains, Array
          cprop :zimbraPrefOutOfOfficeStatusAlertOnLogin, _Boolean
          cprop :zimbraPrefOutOfOfficeSuppressExternalReply, _Boolean
          cprop :zimbraPrefOutOfOfficeUntilDate, String
          cprop :zimbraPrefPop3DeleteOption, String
          cprop :zimbraPrefPop3DownloadSince, String
          cprop :zimbraPrefPop3IncludeSpam, _Boolean
          cprop :zimbraPrefQuickCommand, Array
          cprop :zimbraPrefReadingPaneLocation, String
          cprop :zimbraPrefReplyIncludeOriginalText, String
          cprop :zimbraPrefReplyToAddress, String
          cprop :zimbraPrefReplyToDisplay, String
          cprop :zimbraPrefReplyToEnabled, _Boolean
          cprop :zimbraPrefSaveToSent, _Boolean
          cprop :zimbraPrefSearchTreeOpen, _Boolean
          cprop :zimbraPrefSentLifetime, String
          cprop :zimbraPrefSentMailFolder, String
          cprop :zimbraPrefSharedAddrBookAutoCompleteEnabled, _Boolean
          cprop :zimbraPrefShortEmailAddress, _Boolean
          cprop :zimbraPrefShortcuts, String
          cprop :zimbraPrefShowAllNewMailNotifications, _Boolean
          cprop :zimbraPrefShowCalendarWeek, _Boolean
          cprop :zimbraPrefShowChatsFolderInMail, _Boolean
          cprop :zimbraPrefShowComposeDirection, _Boolean
          cprop :zimbraPrefShowFragments, _Boolean
          cprop :zimbraPrefShowSearchString, _Boolean
          cprop :zimbraPrefShowSelectionCheckbox, _Boolean
          cprop :zimbraPrefSkin, String
          cprop :zimbraPrefSortOrder, String
          cprop :zimbraPrefSpellDictionary, String
          cprop :zimbraPrefSpellIgnoreAllCaps, _Boolean
          cprop :zimbraPrefSpellIgnorePattern, String
          cprop :zimbraPrefSpellIgnoreWord, Array
          cprop :zimbraPrefStandardClientAccessibilityMode, _Boolean
          cprop :zimbraPrefTabInEditorEnabled, _Boolean
          cprop :zimbraPrefTagTreeOpen, _Boolean
          cprop :zimbraPrefTasksFilterBy, String
          cprop :zimbraPrefTasksReadingPaneLocation, String
          cprop :zimbraPrefTimeZoneId, Array
          cprop :zimbraPrefTrashLifetime, String
          cprop :zimbraPrefUseKeyboardShortcuts, _Boolean
          cprop :zimbraPrefUseRfc2231, _Boolean
          cprop :zimbraPrefUseSendMsgShortcut, _Boolean
          cprop :zimbraPrefUseTimeZoneListInCalendar, _Boolean
          cprop :zimbraPrefVoiceItemsPerPage, Integer
          cprop :zimbraPrefWarnOnExit, _Boolean
          cprop :zimbraPrefWebClientOfflineBrowserKey, Array
          cprop :zimbraPrefWhenInFolderIds, Array
          cprop :zimbraPrefWhenInFoldersEnabled, _Boolean
          cprop :zimbraPrefWhenSentToAddresses, Array
          cprop :zimbraPrefWhenSentToEnabled, _Boolean
          cprop :zimbraPrefZimletTreeOpen, _Boolean
          cprop :zimbraPrefZimlets, Array
          cprop :zimbraPrefZmgPushNotificationEnabled, _Boolean
          cprop :zimbraProxyAllowedDomains, Array
          cprop :zimbraPublicShareLifetime, String
          cprop :zimbraPublicSharingEnabled, _Boolean
          cprop :zimbraQuotaLastWarnTime, String, immutable: true
          cprop :zimbraQuotaWarnInterval, String
          cprop :zimbraQuotaWarnMessage, String
          cprop :zimbraQuotaWarnPercent, Integer
          cprop :zimbraRecoveryAccountCodeValidity, String
          cprop :zimbraResetPasswordRecoveryCodeExpiry, String
          cprop :zimbraReverseProxyUseExternalRoute, _Boolean
          cprop :zimbraRevokeAppSpecificPasswordsOnPasswordChange, _Boolean
          cprop :zimbraShareLifetime, String
          cprop :zimbraSharedItem, Array
          cprop :zimbraShowClientTOS, _Boolean
          cprop :zimbraSieveEditHeaderEnabled, _Boolean
          cprop :zimbraSieveImmutableHeaders, String
          cprop :zimbraSieveNotifyActionRFCCompliant, _Boolean
          cprop :zimbraSieveRejectMailEnabled, _Boolean
          cprop :zimbraSieveRequireControlEnabled, _Boolean
          cprop :zimbraSignatureId, String
          cprop :zimbraSignatureMaxNumEntries, Integer
          cprop :zimbraSignatureMinNumEntries, Integer
          cprop :zimbraSignatureName, String
          cprop :zimbraSmtpEnableTrace, _Boolean
          cprop :zimbraSmtpRestrictEnvelopeFrom, _Boolean
          cprop :zimbraSocialcastURL, String
          cprop :zimbraSpamApplyUserFilters, _Boolean
          cprop :zimbraStandardClientCustomPrefTab, Array
          cprop :zimbraStandardClientCustomPrefTabsEnabled, _Boolean
          cprop :zimbraSyncWindowSize, Integer
          cprop :zimbraTextAnalyzer, String
          cprop :zimbraTouchJSErrorTrackingEnabled, _Boolean
          cprop :zimbraTouchJSErrorTrackingKey, String
          cprop :zimbraTwoFactorAuthEnabled, _Boolean
          cprop :zimbraTwoFactorAuthEnablementTokenLifetime, String
          cprop :zimbraTwoFactorAuthLockoutFailureTime, Array
          cprop :zimbraTwoFactorAuthLockoutMaxFailures, Integer
          cprop :zimbraTwoFactorAuthNumScratchCodes, Integer
          cprop :zimbraTwoFactorAuthScratchCodes, String, immutable: true
          cprop :zimbraTwoFactorAuthSecret, String, immutable: true
          cprop :zimbraTwoFactorAuthTokenLifetime, String
          cprop :zimbraTwoFactorAuthTrustedDeviceTokenLifetime, String
          cprop :zimbraTwoFactorAuthTrustedDevices, Array, immutable: true
          cprop :zimbraUCPassword, String
          cprop :zimbraUCServiceId, String
          cprop :zimbraUCUsername, String
          cprop :zimbraVersion, Integer
          cprop :zimbraVirtualAccountInitialPasswordSet, _Boolean
          cprop :zimbraWebClientOfflineSyncMaxDays, Integer
          cprop :zimbraWebClientShowOfflineLink, _Boolean
          cprop :zimbraYahooId, String
          cprop :zimbraZimletAvailableZimlets, Array
          cprop :zimbraZimletLoadSynchronously, _Boolean
          cprop :zimbraZimletUserProperties, Array
          cprop :zimbraZimletUserPropertiesMaxNumEntries, Integer

          def self.create_keys
            return @create_keys if defined?(@create_keys)

            @create_keys = philosophal_properties.mutables.keys - %i[zimbraMailTransport]
          end

          def self.update_keys
            return @update_keys if defined?(@update_keys)

            @update_keys = philosophal_properties.mutables.keys - %i[zimbraMailHost]
          end
        end
      end
    end
  end
end
