# frozen_string_literal: true

module Zm
  module Client
    module ServerAttrs
      def self.included(base)
        base.class_eval do
          extend Philosophal::Properties

          cprop :zimbraActiveSyncEhcacheExpiration, String
          cprop :zimbraActiveSyncEhcacheHeapSize, Integer
          cprop :zimbraActiveSyncEhcacheMaxDiskSize, Integer
          cprop :zimbraAdminImapImportNumThreads, Integer
          cprop :zimbraAdminPort, Integer
          cprop :zimbraAdminProxyPort, Integer
          cprop :zimbraAdminSieveFeatureVariablesEnabled, _Boolean
          cprop :zimbraAdminURL, String
          cprop :zimbraAmavisDSPAMEnabled, _Boolean
          cprop :zimbraAmavisEnableDKIMVerification, _Boolean
          cprop :zimbraAmavisFinalSpamDestiny, String
          cprop :zimbraAmavisLogLevel, Integer
          cprop :zimbraAmavisMaxServers, Integer
          cprop :zimbraAmavisOriginatingBypassSA, _Boolean
          cprop :zimbraAmavisSALogLevel, Integer
          cprop :zimbraAntispamExtractionBatchDelay, Integer
          cprop :zimbraAntispamExtractionBatchSize, Integer
          cprop :zimbraAttachmentsIndexedTextLimit, Integer
          cprop :zimbraAuthTokenNotificationInterval, Integer
          cprop :zimbraAutoProvPollingInterval, String
          cprop :zimbraBackupAutoGroupedInterval, String
          cprop :zimbraBackupAutoGroupedNumGroups, Integer
          cprop :zimbraBackupAutoGroupedThrottled, _Boolean
          cprop :zimbraBackupMinFreeSpace, Integer
          cprop :zimbraBackupMode, String
          cprop :zimbraBackupReportEmailSubjectPrefix, String
          cprop :zimbraBackupSkipBlobs, _Boolean
          cprop :zimbraBackupSkipHsmBlobs, _Boolean
          cprop :zimbraBackupSkipSearchIndex, _Boolean
          cprop :zimbraBackupTarget, String
          cprop :zimbraCBPolicydAccessControlEnabled, _Boolean
          cprop :zimbraCBPolicydAccountingEnabled, _Boolean
          cprop :zimbraCBPolicydAmavisEnabled, _Boolean
          cprop :zimbraCBPolicydBindPort, Integer
          cprop :zimbraCBPolicydBypassMode, String
          cprop :zimbraCBPolicydBypassTimeout, Integer
          cprop :zimbraCBPolicydCheckHeloEnabled, _Boolean
          cprop :zimbraCBPolicydCheckSPFEnabled, _Boolean
          cprop :zimbraCBPolicydGreylistingBlacklistMsg, String
          cprop :zimbraCBPolicydGreylistingDeferMsg, String
          cprop :zimbraCBPolicydGreylistingEnabled, _Boolean
          cprop :zimbraCBPolicydGreylistingTrainingEnabled, _Boolean
          cprop :zimbraCBPolicydLogLevel, Integer
          cprop :zimbraCBPolicydMaxRequests, Integer
          cprop :zimbraCBPolicydMaxServers, Integer
          cprop :zimbraCBPolicydMaxSpareServers, Integer
          cprop :zimbraCBPolicydMinServers, Integer
          cprop :zimbraCBPolicydMinSpareServers, Integer
          cprop :zimbraCBPolicydQuotasEnabled, _Boolean
          cprop :zimbraCBPolicydTimeoutBusy, Integer
          cprop :zimbraCBPolicydTimeoutIdle, Integer
          cprop :zimbraCalendarCalDavClearTextPasswordEnabled, _Boolean
          cprop :zimbraCalendarCalDavDefaultCalendarId, Integer
          cprop :zimbraCalendarRecurrenceDailyMaxDays, Integer
          cprop :zimbraCalendarRecurrenceMaxInstances, Integer
          cprop :zimbraCalendarRecurrenceMonthlyMaxMonths, Integer
          cprop :zimbraCalendarRecurrenceOtherFrequencyMaxYears, Integer
          cprop :zimbraCalendarRecurrenceWeeklyMaxWeeks, Integer
          cprop :zimbraCalendarRecurrenceYearlyMaxYears, Integer
          cprop :zimbraChatAllowUnencryptedPassword, _Boolean
          cprop :zimbraChatServiceEnabled, _Boolean
          cprop :zimbraChatXmppPort, Integer
          cprop :zimbraChatXmppSslPort, Integer
          cprop :zimbraChatXmppSslPortEnabled, _Boolean
          cprop :zimbraClamAVBindAddress, String
          cprop :zimbraClamAVDatabaseMirror, String
          cprop :zimbraClamAVListenPort, Integer
          cprop :zimbraClamAVMaxThreads, Integer
          cprop :zimbraClamAVSafeBrowsing, String
          cprop :zimbraClusterType, String
          cprop :zimbraConfiguredServerIDForBlobDirEnabled, _Boolean
          cprop :zimbraContactHiddenAttributes, String
          cprop :zimbraContactRankingTableRefreshInterval, String
          cprop :zimbraContactSearchDecomposition, Integer
          cprop :zimbraConvertPoolTimeout, Integer
          cprop :zimbraCreateTimestamp, String
          cprop :zimbraDNSTCPUpstream, String
          cprop :zimbraDNSUseTCP, String
          cprop :zimbraDNSUseUDP, String
          cprop :zimbraDatabaseSlowSqlThreshold, String
          cprop :zimbraEmptyFolderOpTimeout, Integer
          cprop :zimbraExtensionBindPort, Integer
          cprop :zimbraExternalAccountStatusCheckInterval, String
          cprop :zimbraFeatureContactBackupFrequency, Integer
          cprop :zimbraFeatureContactBackupLifeTime, String
          cprop :zimbraFileUploadMaxSize, Integer
          cprop :zimbraFreebusyPropagationRetryInterval, String
          cprop :zimbraHsmAge, String
          cprop :zimbraHsmBatchSize, Integer
          cprop :zimbraHsmMovePreviousRevisions, _Boolean
          cprop :zimbraHsmPolicy, String
          cprop :zimbraHttpCompressionEnabled, _Boolean
          cprop :zimbraHttpConnectorMaxIdleTimeMillis, Integer
          cprop :zimbraHttpContextPathBasedThreadPoolBalancingFilterRules, Array
          cprop :zimbraHttpDebugHandlerEnabled, _Boolean
          cprop :zimbraHttpDosFilterDelayMillis, Integer
          cprop :zimbraHttpDosFilterMaxRequestsPerSec, Integer
          cprop :zimbraHttpHeaderCacheSize, Integer
          cprop :zimbraHttpMaxFormContentSize, Integer
          cprop :zimbraHttpNumThreads, Integer
          cprop :zimbraHttpOutputBufferSize, Integer
          cprop :zimbraHttpRequestHeaderSize, Integer
          cprop :zimbraHttpResponseHeaderSize, Integer
          cprop :zimbraHttpSSLNumThreads, Integer
          cprop :zimbraHttpThreadPoolMaxIdleTimeMillis, Integer
          cprop :zimbraHttpThrottleSafeIPs, Array
          cprop :zimbraIPMode, String
          cprop :zimbraId, String
          cprop :zimbraImapActiveSessionEhcacheMaxDiskSize, Integer
          cprop :zimbraImapBindOnStartup, _Boolean
          cprop :zimbraImapBindPort, Integer
          cprop :zimbraImapCleartextLoginEnabled, _Boolean
          cprop :zimbraImapDisplayMailFoldersOnly, _Boolean
          cprop :zimbraImapExposeVersionOnBanner, _Boolean
          cprop :zimbraImapInactiveSessionCacheMaxDiskSize, Integer
          cprop :zimbraImapInactiveSessionEhcacheMaxDiskSize, Integer
          cprop :zimbraImapInactiveSessionEhcacheSize, Integer
          cprop :zimbraImapLoadBalancingAlgorithm, String
          cprop :zimbraImapMaxConnections, Integer
          cprop :zimbraImapMaxRequestSize, Integer
          cprop :zimbraImapNumThreads, Integer
          cprop :zimbraImapProxyBindPort, Integer
          cprop :zimbraImapSSLBindOnStartup, _Boolean
          cprop :zimbraImapSSLBindPort, Integer
          cprop :zimbraImapSSLProxyBindPort, Integer
          cprop :zimbraImapSSLServerEnabled, _Boolean
          cprop :zimbraImapSaslGssapiEnabled, _Boolean
          cprop :zimbraImapServerEnabled, _Boolean
          cprop :zimbraImapShutdownGraceSeconds, Integer
          cprop :zimbraInvalidLoginFilterDelayInMinBetwnReqBeforeReinstating, Integer
          cprop :zimbraInvalidLoginFilterMaxFailedLogin, Integer
          cprop :zimbraInvalidLoginFilterMaxSizeOfFailedIpDb, Integer
          cprop :zimbraInvalidLoginFilterReinstateIpTaskIntervalInMin, Integer
          cprop :zimbraItemActionBatchSize, Integer
          cprop :zimbraLastPurgeMaxDuration, String
          cprop :zimbraLdapGentimeFractionalSecondsEnabled, _Boolean
          cprop :zimbraLmtpBindOnStartup, _Boolean
          cprop :zimbraLmtpBindPort, Integer
          cprop :zimbraLmtpExposeVersionOnBanner, _Boolean
          cprop :zimbraLmtpLHLORequired, _Boolean
          cprop :zimbraLmtpNumThreads, Integer
          cprop :zimbraLmtpPermanentFailureWhenOverQuota, _Boolean
          cprop :zimbraLmtpServerEnabled, _Boolean
          cprop :zimbraLmtpShutdownGraceSeconds, Integer
          cprop :zimbraLogToSyslog, _Boolean
          cprop :zimbraLowestSupportedAuthVersion, Integer
          cprop :zimbraMailClearTextPasswordEnabled, _Boolean
          cprop :zimbraMailContentMaxSize, Integer
          cprop :zimbraMailDiskStreamingThreshold, Integer
          cprop :zimbraMailEmptyFolderBatchSize, Integer
          cprop :zimbraMailEmptyFolderBatchThreshold, Integer
          cprop :zimbraMailFileDescriptorBufferSize, Integer
          cprop :zimbraMailFileDescriptorCacheSize, Integer
          cprop :zimbraMailKeepOutWebCrawlers, _Boolean
          cprop :zimbraMailLocalBind, _Boolean
          cprop :zimbraMailMode, String
          cprop :zimbraMailPort, Integer
          cprop :zimbraMailProxyMaxFails, Integer
          cprop :zimbraMailProxyPort, Integer
          cprop :zimbraMailProxyReconnectTimeout, Integer
          cprop :zimbraMailPurgeBatchSize, Integer
          cprop :zimbraMailPurgeSleepInterval, String
          cprop :zimbraMailRedirectSetEnvelopeSender, _Boolean
          cprop :zimbraMailReferMode, String
          cprop :zimbraMailSSLClientCertMode, String
          cprop :zimbraMailSSLClientCertOCSPEnabled, _Boolean
          cprop :zimbraMailSSLClientCertPort, Integer
          cprop :zimbraMailSSLPort, Integer
          cprop :zimbraMailSSLProxyClientCertPort, Integer
          cprop :zimbraMailSSLProxyPort, Integer
          cprop :zimbraMailURL, String
          cprop :zimbraMailUncompressedCacheMaxBytes, Integer
          cprop :zimbraMailUncompressedCacheMaxFiles, Integer
          cprop :zimbraMailUseDirectBuffers, _Boolean
          cprop :zimbraMailboxMoveFailedCleanupTaskInterval, String
          cprop :zimbraMailboxMoveSkipBlobs, _Boolean
          cprop :zimbraMailboxMoveSkipHsmBlobs, _Boolean
          cprop :zimbraMailboxMoveSkipSearchIndex, _Boolean
          cprop :zimbraMailboxMoveTempDir, String
          cprop :zimbraMailboxThrottleReapInterval, String
          cprop :zimbraMailboxdSSLProtocols, Array
          cprop :zimbraMailboxdSSLRenegotiationAllowed, _Boolean
          cprop :zimbraMemcachedBindPort, Integer
          cprop :zimbraMemcachedClientBinaryProtocolEnabled, _Boolean
          cprop :zimbraMemcachedClientExpirySeconds, Integer
          cprop :zimbraMemcachedClientHashAlgorithm, String
          cprop :zimbraMemcachedClientTimeoutMillis, Integer
          cprop :zimbraMessageCacheSize, Integer
          cprop :zimbraMessageChannelEnabled, _Boolean
          cprop :zimbraMessageChannelPort, Integer
          cprop :zimbraMilterBindPort, Integer
          cprop :zimbraMilterMaxConnections, Integer
          cprop :zimbraMilterNumThreads, Integer
          cprop :zimbraMilterServerEnabled, _Boolean
          cprop :zimbraMobileMaxMessageSize, Integer
          cprop :zimbraMobileMetadataRetentionPolicy, String
          cprop :zimbraMtaAddressVerifyNegativeRefreshTime, String
          cprop :zimbraMtaAddressVerifyPollCount, String
          cprop :zimbraMtaAddressVerifyPollDelay, String
          cprop :zimbraMtaAddressVerifyPositiveRefreshTime, String
          cprop :zimbraMtaAliasMaps, String
          cprop :zimbraMtaAlwaysAddMissingHeaders, String
          cprop :zimbraMtaAntiSpamLockMethod, String
          cprop :zimbraMtaAuthEnabled, _Boolean
          cprop :zimbraMtaAuthPort, Integer
          cprop :zimbraMtaAuthTarget, _Boolean
          cprop :zimbraMtaBounceNoticeRecipient, String
          cprop :zimbraMtaBounceQueueLifetime, String
          cprop :zimbraMtaBrokenSaslAuthClients, String
          cprop :zimbraMtaCanonicalMaps, String
          cprop :zimbraMtaCommandDirectory, String
          cprop :zimbraMtaDaemonDirectory, String
          cprop :zimbraMtaDefaultProcessLimit, Integer
          cprop :zimbraMtaDelayWarningTime, String
          cprop :zimbraMtaDnsLookupsEnabled, _Boolean
          cprop :zimbraMtaEnableSmtpdPolicyd, _Boolean
          cprop :zimbraMtaHeaderChecks, String
          cprop :zimbraMtaHopcountLimit, Integer
          cprop :zimbraMtaInFlowDelay, String
          cprop :zimbraMtaLmdbMapSize, Integer
          cprop :zimbraMtaLmtpConnectionCacheTimeLimit, String
          cprop :zimbraMtaLmtpHostLookup, String
          cprop :zimbraMtaLmtpTlsCiphers, String
          cprop :zimbraMtaLmtpTlsLoglevel, Integer
          cprop :zimbraMtaLmtpTlsMandatoryCiphers, String
          cprop :zimbraMtaLmtpTlsMandatoryProtocols, String
          cprop :zimbraMtaLmtpTlsProtocols, String
          cprop :zimbraMtaLmtpTlsSecurityLevel, String
          cprop :zimbraMtaMailqPath, String
          cprop :zimbraMtaManpageDirectory, String
          cprop :zimbraMtaMaxUse, Integer
          cprop :zimbraMtaMaximalBackoffTime, String
          cprop :zimbraMtaMaximalQueueLifetime, String
          cprop :zimbraMtaMilterCommandTimeout, String
          cprop :zimbraMtaMilterConnectTimeout, String
          cprop :zimbraMtaMilterContentTimeout, String
          cprop :zimbraMtaMilterDefaultAction, String
          cprop :zimbraMtaMinimalBackoffTime, String
          cprop :zimbraMtaMyDestination, String
          cprop :zimbraMtaMyNetworks, String
          cprop :zimbraMtaNewaliasesPath, String
          cprop :zimbraMtaNotifyClasses, Array
          cprop :zimbraMtaPolicyTimeLimit, Integer
          cprop :zimbraMtaPostscreenAccessList, String
          cprop :zimbraMtaPostscreenBareNewlineAction, String
          cprop :zimbraMtaPostscreenBareNewlineEnable, String
          cprop :zimbraMtaPostscreenBareNewlineTTL, String
          cprop :zimbraMtaPostscreenBlacklistAction, String
          cprop :zimbraMtaPostscreenCacheCleanupInterval, String
          cprop :zimbraMtaPostscreenCacheRetentionTime, String
          cprop :zimbraMtaPostscreenCommandCountLimit, Integer
          cprop :zimbraMtaPostscreenDnsblAction, String
          cprop :zimbraMtaPostscreenDnsblMaxTTL, String
          cprop :zimbraMtaPostscreenDnsblMinTTL, String
          cprop :zimbraMtaPostscreenDnsblTTL, String
          cprop :zimbraMtaPostscreenDnsblThreshold, Integer
          cprop :zimbraMtaPostscreenDnsblTimeout, String
          cprop :zimbraMtaPostscreenDnsblWhitelistThreshold, Integer
          cprop :zimbraMtaPostscreenGreetAction, String
          cprop :zimbraMtaPostscreenGreetTTL, String
          cprop :zimbraMtaPostscreenNonSmtpCommandAction, String
          cprop :zimbraMtaPostscreenNonSmtpCommandEnable, String
          cprop :zimbraMtaPostscreenNonSmtpCommandTTL, String
          cprop :zimbraMtaPostscreenPipeliningAction, String
          cprop :zimbraMtaPostscreenPipeliningEnable, String
          cprop :zimbraMtaPostscreenPipeliningTTL, String
          cprop :zimbraMtaPostscreenWatchdogTimeout, String
          cprop :zimbraMtaPostscreenWhitelistInterfaces, String
          cprop :zimbraMtaPropagateUnmatchedExtensions, String
          cprop :zimbraMtaQueueDirectory, String
          cprop :zimbraMtaQueueRunDelay, String
          cprop :zimbraMtaRestriction, Array
          cprop :zimbraMtaSaslAuthEnable, String
          cprop :zimbraMtaSaslSmtpdMechList, Array
          cprop :zimbraMtaSendmailPath, String
          cprop :zimbraMtaSmtpCnameOverridesServername, String
          cprop :zimbraMtaSmtpDnsSupportLevel, String
          cprop :zimbraMtaSmtpHeloName, String
          cprop :zimbraMtaSmtpSaslAuthEnable, String
          cprop :zimbraMtaSmtpSaslSecurityOptions, String
          cprop :zimbraMtaSmtpTlsCiphers, String
          cprop :zimbraMtaSmtpTlsDaneInsecureMXPolicy, String
          cprop :zimbraMtaSmtpTlsLoglevel, Integer
          cprop :zimbraMtaSmtpTlsMandatoryCiphers, String
          cprop :zimbraMtaSmtpTlsMandatoryProtocols, String
          cprop :zimbraMtaSmtpTlsProtocols, String
          cprop :zimbraMtaSmtpTlsSecurityLevel, String
          cprop :zimbraMtaSmtpTransportRateDelay, String
          cprop :zimbraMtaSmtpdBanner, String
          cprop :zimbraMtaSmtpdClientAuthRateLimit, Integer
          cprop :zimbraMtaSmtpdClientPortLogging, String
          cprop :zimbraMtaSmtpdClientRestrictions, String
          cprop :zimbraMtaSmtpdDataRestrictions, String
          cprop :zimbraMtaSmtpdErrorSleepTime, String
          cprop :zimbraMtaSmtpdHardErrorLimit, Integer
          cprop :zimbraMtaSmtpdHeloRequired, String
          cprop :zimbraMtaSmtpdProxyTimeout, String
          cprop :zimbraMtaSmtpdRejectUnlistedRecipient, String
          cprop :zimbraMtaSmtpdRejectUnlistedSender, String
          cprop :zimbraMtaSmtpdSaslAuthenticatedHeader, String
          cprop :zimbraMtaSmtpdSaslSecurityOptions, String
          cprop :zimbraMtaSmtpdSaslTlsSecurityOptions, String
          cprop :zimbraMtaSmtpdSoftErrorLimit, Integer
          cprop :zimbraMtaSmtpdTlsAskCcert, String
          cprop :zimbraMtaSmtpdTlsCcertVerifydepth, Integer
          cprop :zimbraMtaSmtpdTlsCiphers, String
          cprop :zimbraMtaSmtpdTlsLoglevel, Integer
          cprop :zimbraMtaSmtpdTlsMandatoryCiphers, String
          cprop :zimbraMtaSmtpdTlsMandatoryProtocols, String
          cprop :zimbraMtaSmtpdTlsProtocols, String
          cprop :zimbraMtaSmtpdTlsReceivedHeader, String
          cprop :zimbraMtaSmtpdVirtualTransport, String
          cprop :zimbraMtaStpdSoftErrorLimit, Integer
          cprop :zimbraMtaTlsAppendDefaultCA, String
          cprop :zimbraMtaTlsAuthOnly, _Boolean
          cprop :zimbraMtaTlsSecurityLevel, String
          cprop :zimbraMtaTransportMaps, String
          cprop :zimbraMtaUnverifiedRecipientDeferCode, Integer
          cprop :zimbraMtaVirtualAliasDomains, String
          cprop :zimbraMtaVirtualAliasExpansionLimit, Integer
          cprop :zimbraMtaVirtualAliasMaps, String
          cprop :zimbraMtaVirtualMailboxDomains, String
          cprop :zimbraMtaVirtualMailboxMaps, String
          cprop :zimbraNetworkAdminEnabled, _Boolean
          cprop :zimbraNetworkAdminNGEnabled, _Boolean
          cprop :zimbraNetworkMobileNGEnabled, _Boolean
          cprop :zimbraNetworkModulesNGEnabled, _Boolean
          cprop :zimbraNotebookFolderCacheSize, Integer
          cprop :zimbraNotebookMaxCachedTemplatesPerFolder, Integer
          cprop :zimbraNotebookPageCacheSize, Integer
          cprop :zimbraNotifyBindPort, Integer
          cprop :zimbraNotifySSLBindPort, Integer
          cprop :zimbraNotifySSLServerEnabled, _Boolean
          cprop :zimbraNotifyServerEnabled, _Boolean
          cprop :zimbraOpenImapFolderRequestChunkSize, Integer
          cprop :zimbraOpenidConsumerStatelessModeEnabled, _Boolean
          cprop :zimbraPop3BindOnStartup, _Boolean
          cprop :zimbraPop3BindPort, Integer
          cprop :zimbraPop3CleartextLoginEnabled, _Boolean
          cprop :zimbraPop3ExposeVersionOnBanner, _Boolean
          cprop :zimbraPop3MaxConnections, Integer
          cprop :zimbraPop3NumThreads, Integer
          cprop :zimbraPop3ProxyBindPort, Integer
          cprop :zimbraPop3SSLBindOnStartup, _Boolean
          cprop :zimbraPop3SSLBindPort, Integer
          cprop :zimbraPop3SSLProxyBindPort, Integer
          cprop :zimbraPop3SSLServerEnabled, _Boolean
          cprop :zimbraPop3SaslGssapiEnabled, _Boolean
          cprop :zimbraPop3ServerEnabled, _Boolean
          cprop :zimbraPop3ShutdownGraceSeconds, Integer
          cprop :zimbraPrevFoldersToTrackMax, Integer
          cprop :zimbraRedoLogArchiveDir, String
          cprop :zimbraRedoLogCrashRecoveryLookbackSec, Integer
          cprop :zimbraRedoLogDeleteOnRollover, _Boolean
          cprop :zimbraRedoLogEnabled, _Boolean
          cprop :zimbraRedoLogFsyncIntervalMS, Integer
          cprop :zimbraRedoLogLogPath, String
          cprop :zimbraRedoLogRolloverFileSizeKB, Integer
          cprop :zimbraRedoLogRolloverHardMaxFileSizeKB, Integer
          cprop :zimbraRedoLogRolloverMinFileAge, Integer
          cprop :zimbraRemoteImapBindPort, Integer
          cprop :zimbraRemoteImapSSLBindPort, Integer
          cprop :zimbraRemoteImapSSLServerEnabled, _Boolean
          cprop :zimbraRemoteImapServerEnabled, _Boolean
          cprop :zimbraRemoteManagementCommand, String
          cprop :zimbraRemoteManagementPort, Integer
          cprop :zimbraRemoteManagementPrivateKeyPath, String
          cprop :zimbraRemoteManagementUser, String
          cprop :zimbraReverseProxyAcceptMutex, String
          cprop :zimbraReverseProxyAdminEnabled, _Boolean
          cprop :zimbraReverseProxyAvailableLookupTargets, String
          cprop :zimbraReverseProxyClientCertMode, String
          cprop :zimbraReverseProxyConnectTimeout, String
          cprop :zimbraReverseProxyDnsLookupInServerEnabled, _Boolean
          cprop :zimbraReverseProxyExactServerVersionCheck, String
          cprop :zimbraReverseProxyGenConfigPerVirtualHostname, _Boolean
          cprop :zimbraReverseProxyHttpEnabled, _Boolean
          cprop :zimbraReverseProxyIPThrottleWhitelistTime, String
          cprop :zimbraReverseProxyImapEnabledCapability, Array
          cprop :zimbraReverseProxyImapExposeVersionOnBanner, _Boolean
          cprop :zimbraReverseProxyImapSaslGssapiEnabled, _Boolean
          cprop :zimbraReverseProxyImapSaslPlainEnabled, _Boolean
          cprop :zimbraReverseProxyImapStartTlsMode, String
          cprop :zimbraReverseProxyInactivityTimeout, String
          cprop :zimbraReverseProxyLogLevel, String
          cprop :zimbraReverseProxyLookupTarget, _Boolean
          cprop :zimbraReverseProxyMailEnabled, _Boolean
          cprop :zimbraReverseProxyMailImapEnabled, _Boolean
          cprop :zimbraReverseProxyMailImapsEnabled, _Boolean
          cprop :zimbraReverseProxyMailMode, String
          cprop :zimbraReverseProxyMailPop3Enabled, _Boolean
          cprop :zimbraReverseProxyMailPop3sEnabled, _Boolean
          cprop :zimbraReverseProxyPassErrors, _Boolean
          cprop :zimbraReverseProxyPop3EnabledCapability, Array
          cprop :zimbraReverseProxyPop3ExposeVersionOnBanner, _Boolean
          cprop :zimbraReverseProxyPop3SaslGssapiEnabled, _Boolean
          cprop :zimbraReverseProxyPop3SaslPlainEnabled, _Boolean
          cprop :zimbraReverseProxyPop3StartTlsMode, String
          cprop :zimbraReverseProxyRouteLookupTimeout, String
          cprop :zimbraReverseProxyRouteLookupTimeoutCache, String
          cprop :zimbraReverseProxySNIEnabled, _Boolean
          cprop :zimbraReverseProxySSLCiphers, String
          cprop :zimbraReverseProxySSLProtocols, Array
          cprop :zimbraReverseProxySSLSessionCacheSize, String
          cprop :zimbraReverseProxySSLSessionTimeout, String
          cprop :zimbraReverseProxySSLToUpstreamEnabled, _Boolean
          cprop :zimbraReverseProxyStrictServerNameEnabled, _Boolean
          cprop :zimbraReverseProxyUpstreamConnectTimeout, Integer
          cprop :zimbraReverseProxyUpstreamFairShmSize, Integer
          cprop :zimbraReverseProxyUpstreamLoginServers, String
          cprop :zimbraReverseProxyUpstreamPollingTimeout, String
          cprop :zimbraReverseProxyUpstreamReadTimeout, String
          cprop :zimbraReverseProxyUpstreamSendTimeout, String
          cprop :zimbraReverseProxyWorkerConnections, Integer
          cprop :zimbraReverseProxyWorkerProcesses, Integer
          cprop :zimbraReverseProxyXmppBoshEnabled, _Boolean
          cprop :zimbraReverseProxyXmppBoshLocalHttpBindURL, String
          cprop :zimbraReverseProxyXmppBoshSSL, _Boolean
          cprop :zimbraReverseProxyXmppBoshTimeout, String
          cprop :zimbraReverseProxyZmlookupCachingEnabled, _Boolean
          cprop :zimbraSSLCertificate, String
          cprop :zimbraSSLExcludeCipherSuites, String
          cprop :zimbraSSLPrivateKey, String
          cprop :zimbraSaslGssapiRequiresTls, _Boolean
          cprop :zimbraScheduledTaskNumThreads, Integer
          cprop :zimbraServerVersion, String
          cprop :zimbraServerVersionBuild, Integer
          cprop :zimbraServerVersionMajor, Integer
          cprop :zimbraServerVersionMicro, Integer
          cprop :zimbraServerVersionMinor, Integer
          cprop :zimbraServerVersionType, String
          cprop :zimbraServiceEnabled, Array
          cprop :zimbraServiceHostname, String
          cprop :zimbraServiceInstalled, Array
          cprop :zimbraShareNotificationMtaAuthRequired, _Boolean
          cprop :zimbraShareNotificationMtaConnectionType, String
          cprop :zimbraShareNotificationMtaEnabled, _Boolean
          cprop :zimbraSharingUpdatePublishInterval, String
          cprop :zimbraShortTermAllEffectiveRightsCacheExpiration, String
          cprop :zimbraShortTermAllEffectiveRightsCacheSize, Integer
          cprop :zimbraShortTermGranteeCacheExpiration, String
          cprop :zimbraShortTermGranteeCacheSize, Integer
          cprop :zimbraSieveFeatureVariablesEnabled, _Boolean
          cprop :zimbraSieveRejectEnabled, _Boolean
          cprop :zimbraSmimeOCSPEnabled, _Boolean
          cprop :zimbraSmtpHostname, String
          cprop :zimbraSmtpPort, Integer
          cprop :zimbraSmtpSendPartial, _Boolean
          cprop :zimbraSmtpTimeout, Integer
          cprop :zimbraSoapExposeVersion, _Boolean
          cprop :zimbraSoapRequestMaxSize, Integer
          cprop :zimbraSpellAvailableDictionary, String
          cprop :zimbraSpellCheckURL, String
          cprop :zimbraSshPublicKey, String
          cprop :zimbraStatThreadNamePrefix, Array
          cprop :zimbraTableMaintenanceGrowthFactor, Integer
          cprop :zimbraTableMaintenanceMaxRows, Integer
          cprop :zimbraTableMaintenanceMinRows, Integer
          cprop :zimbraTableMaintenanceOperation, String
          cprop :zimbraThreadMonitorEnabled, _Boolean
          cprop :zimbraVirusDefinitionsUpdateFrequency, String
          cprop :zimbraWebGzipEnabled, _Boolean
          cprop :zimbraXMPPEnabled, _Boolean
          cprop :zimbraZimletJspEnabled, _Boolean
        end
      end
    end
  end
end
