# frozen_string_literal: true

module Zm
  module Client
    module SoapAccountConstants
      ACCOUNT_SERVICE_URI = '/service/soap/'

      NAMESPACE_STR = 'urn:zimbraAccount'

      AUTH_REQUEST = 'AuthRequest'
      AUTO_COMPLETE_GAL_REQUEST = 'AutoCompleteGalRequest'
      BOOTSTRAP_MOBILE_GATEWAY_APP_REQUEST = 'BootstrapMobileGatewayAppRequest'
      CHANGE_PASSWORD_REQUEST = 'ChangePasswordRequest'
      CHECK_LICENSE_REQUEST = 'CheckLicenseRequest'
      CHECK_RIGHTS_REQUEST = 'CheckRightsRequest'
      CREATE_APP_SPECIFIC_PASSWORD_REQUEST = 'CreateAppSpecificPasswordRequest'
      CREATE_DISTRIBUTION_LIST_REQUEST = 'CreateDistributionListRequest'
      CREATE_IDENTITY_REQUEST = 'CreateIdentityRequest'
      CREATE_SIGNATURE_REQUEST = 'CreateSignatureRequest'
      DELETE_IDENTITY_REQUEST = 'DeleteIdentityRequest'
      DELETE_SIGNATURE_REQUEST = 'DeleteSignatureRequest'
      DISABLE_TWO_FACTOR_AUTH_REQUEST = 'DisableTwoFactorAuthRequest'
      DISCOVER_RIGHTS_REQUEST = 'DiscoverRightsRequest'
      DISTRIBUTION_LIST_ACTION_REQUEST = 'DistributionListActionRequest'
      ENABLE_TWO_FACTOR_AUTH_REQUEST = 'EnableTwoFactorAuthRequest'
      END_SESSION_REQUEST = 'EndSessionRequest'
      GENERATE_SCRATCH_CODES_REQUEST = 'GenerateScratchCodesRequest'
      GET_ACCOUNT_DISTRIBUTION_LISTS_REQUEST = 'GetAccountDistributionListsRequest'
      GET_ACCOUNT_INFO_REQUEST = 'GetAccountInfoRequest'
      GET_ADDRESS_LIST_MEMBERS_REQUEST = 'GetAddressListMembersRequest'
      GET_ALL_ADDRESS_LISTS_REQUEST = 'GetAllAddressListsRequest'
      GET_ALL_LOCALES_REQUEST = 'GetAllLocalesRequest'
      GET_APP_SPECIFIC_PASSWORDS_REQUEST = 'GetAppSpecificPasswordsRequest'
      GET_AVAILABLE_CSV_FORMATS_REQUEST = 'GetAvailableCsvFormatsRequest'
      GET_AVAILABLE_LOCALES_REQUEST = 'GetAvailableLocalesRequest'
      GET_AVAILABLE_SKINS_REQUEST = 'GetAvailableSkinsRequest'
      GET_DISTRIBUTION_LIST_REQUEST = 'GetDistributionListRequest'
      GET_DISTRIBUTION_LIST_MEMBERS_REQUEST = 'GetDistributionListMembersRequest'
      GET_GCM_SENDER_ID_REQUEST = 'GetGcmSenderIdRequest'
      GET_HAB_REQUEST = 'GetHABRequest'
      GET_IDENTITIES_REQUEST = 'GetIdentitiesRequest'
      GET_INFO_REQUEST = 'GetInfoRequest'
      GET_O_AUTH_CONSUMERS_REQUEST = 'GetOAuthConsumersRequest'
      GET_PREFS_REQUEST = 'GetPrefsRequest'
      GET_RIGHTS_REQUEST = 'GetRightsRequest'
      GET_SMIME_PUBLIC_CERTS_REQUEST = 'GetSMIMEPublicCertsRequest'
      GET_SCRATCH_CODES_REQUEST = 'GetScratchCodesRequest'
      GET_SHARE_INFO_REQUEST = 'GetShareInfoRequest'
      GET_SIGNATURES_REQUEST = 'GetSignaturesRequest'
      GET_SMIME_CERTIFICATE_INFO_REQUEST = 'GetSmimeCertificateInfoRequest'
      GET_TRUSTED_DEVICES_REQUEST = 'GetTrustedDevicesRequest'
      GET_VERSION_INFO_REQUEST = 'GetVersionInfoRequest'
      GET_WHITE_BLACK_LIST_REQUEST = 'GetWhiteBlackListRequest'
      GRANT_RIGHTS_REQUEST = 'GrantRightsRequest'
      MODIFY_IDENTITY_REQUEST = 'ModifyIdentityRequest'
      MODIFY_PREFS_REQUEST = 'ModifyPrefsRequest'
      MODIFY_PROPERTIES_REQUEST = 'ModifyPropertiesRequest'
      MODIFY_SIGNATURE_REQUEST = 'ModifySignatureRequest'
      MODIFY_WHITE_BLACK_LIST_REQUEST = 'ModifyWhiteBlackListRequest'
      MODIFY_ZIMLET_PREFS_REQUEST = 'ModifyZimletPrefsRequest'
      REGISTER_MOBILE_GATEWAY_APP_REQUEST = 'RegisterMobileGatewayAppRequest'
      RENEW_MOBILE_GATEWAY_APP_TOKEN_REQUEST = 'RenewMobileGatewayAppTokenRequest'
      RESET_PASSWORD_REQUEST = 'ResetPasswordRequest'
      REVOKE_APP_SPECIFIC_PASSWORD_REQUEST = 'RevokeAppSpecificPasswordRequest'
      REVOKE_O_AUTH_CONSUMER_REQUEST = 'RevokeOAuthConsumerRequest'
      REVOKE_OTHER_TRUSTED_DEVICES_REQUEST = 'RevokeOtherTrustedDevicesRequest'
      REVOKE_RIGHTS_REQUEST = 'RevokeRightsRequest'
      REVOKE_TRUSTED_DEVICE_REQUEST = 'RevokeTrustedDeviceRequest'
      SAVE_SMIME_CERTIFICATE_REQUEST = 'SaveSmimeCertificateRequest'
      SEARCH_CALENDAR_RESOURCES_REQUEST = 'SearchCalendarResourcesRequest'
      SEARCH_GAL_REQUEST = 'SearchGalRequest'
      SUBSCRIBE_DISTRIBUTION_LIST_REQUEST = 'SubscribeDistributionListRequest'
      SYNC_GAL_REQUEST = 'SyncGalRequest'
    end
  end
end
